<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>SSL</string>
        <key>fileTypes</key>
        <array>
            <string>ssl</string>
        </array>
        <key>foldingStartMarker</key>
	    <string>:\b(IF|WHILE|FOR|TRY|CATCH)\b</string>
	    <key>foldingStopMarker</key>
	    <string>:\b(ENDIF|ENDWHILE|NEXT|CATCH|ENDTRY)\b</string>
        <key>name</key>
        <string>STARLIMS Scripting Language</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#round-brackets</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.asp</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>""</string>
                        <key>name</key>
                        <string>constant.character.escape.apostrophe</string>
                    </dict>
                </array>
            </dict>
            <dict>
			    <key>match</key>
			    <string>-?\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			    <key>name</key>
			    <string>constant.numeric</string>
		    </dict>
            <dict>
                <!-- Numeric (hex) -->
                <key>match</key>
                <string>\b(?i:(0?x)?[0-9a-f][0-9a-f]+)\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <!-- Control Structures -->
            <dict>
                <key>match</key>
                <string>:\b(IF|ELSE|ENDIF|WHILE|ENDWHILE|FOR|TO|NEXT|BEGINCASE|ENDCASE|OTHERWISE|EXITCASE|RETURN|LOOP|EXITWHILE|EXITFOR)\b</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>
            <dict>
			    <key>match</key>
			    <string>(?i:\b(and|not|or)\b)</string>
			    <key>name</key>
			    <string>keyword.operator</string>
		    </dict>
            <dict>
			<key>match</key>
			    <string>!|\*|\-\-|\-|\+\+|\+|==|=|!=|:=|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|\|\||\?\:|\*=|/=|%=|\+=|\-=|&amp;=|\^=</string>
			    <key>name</key>
			    <string>keyword.operator</string>
		    </dict>
            <dict>
			    <key>match</key>
			    <string>(:\b(CLASS|DECLARE|PARAMETERS|DEFAULT|PROCEDURE|ENDPROC|ERROR|RESUME|PUBLIC)\b\s*)</string>
			    <key>name</key>
			    <string>storage.type</string>
		    </dict>
            <dict>
			<key>match</key>
			    <string>(?i:\s*\b(.F.|.T.|nil)\b)</string>
			    <key>name</key>
			    <string>constant.language</string>
		    </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(local))(\:|\b)</string>
                <key>name</key>
                <string>support.function</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(?i:((?&lt;=(\+|=|-|\&amp;|\\|/|&lt;|&gt;|\(|,))\s*\b([a-zA-Z_xf-xff][a-zA-Z0-9_xf-xff]*?)\b(?!(\(|\.))|\b([a-zA-Z_xf-xff][a-zA-Z0-9_xf-xff]*?)\b(?=\s*(\+|=|-|:=|\&amp;|\\|/|&lt;|&gt;|\(|\)))))</string>
                <key>name</key>
                <string>variable.other.asp</string>
            </dict>            
            <dict>
                <key>match</key>
                <string>(?i:(declare)\s*(?:(\b[a-zA-Z_x7f-xff][a-zA-Z0-9_x7f-xff]*?\b)\s*(,?)))</string>
                <key>name</key>
                <string>variable.other.declare</string>
            </dict>            
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?i:(\b[a-zA-Z_x7f-xff][a-zA-Z0-9_x7f-xff]*?\b)(?=\(\)?))</string>
                <key>name</key>
                <string>support.function</string>
            </dict>
        </array>
        
        <key>repository</key>
        <dict>
            <key>round-brackets</key>
            <dict>
                <key>begin</key>
                <string>\(</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.section.round-brackets.begin</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\)</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.section.round-brackets.end</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.round-brackets</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>source.vbs</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>uuid</key>
        <string>ab259404-3072-4cd4-a943-7cbbd32e373f</string>
    </dict>
</plist>